spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
      service-url: 
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  health:
    rabbit:
      enabled: true
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
